import 'text_styles.dart';
import 'theme.dart';
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsnjzsO8cgcAbclG1y7vd5XvrXIQTyCCw',
    appId: '1:601121143669:web:07835952edb39d3e00713c',
    messagingSenderId: '601121143669',
    projectId: 'clubzone-1d568',
    authDomain: 'clubzone-1d568.firebaseapp.com',
    storageBucket: 'clubzone-1d568.firebasestorage.app',
    measurementId: 'G-1Z68LM69ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTNWqn9XR_irgURHEE6Mwy8I0pVO_a7H0',
    appId: '1:601121143669:android:cdc6b5489094a70b00713c',
    messagingSenderId: '601121143669',
    projectId: 'clubzone-1d568',
    storageBucket: 'clubzone-1d568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrMIPwkBzPcVn3gVQ8h8BsBqIjqnlTQnY',
    appId: '1:601121143669:ios:10b17cc6aef38dca00713c',
    messagingSenderId: '601121143669',
    projectId: 'clubzone-1d568',
    storageBucket: 'clubzone-1d568.firebasestorage.app',
    iosBundleId: 'com.example.ds2fcWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrMIPwkBzPcVn3gVQ8h8BsBqIjqnlTQnY',
    appId: '1:601121143669:ios:10b17cc6aef38dca00713c',
    messagingSenderId: '601121143669',
    projectId: 'clubzone-1d568',
    storageBucket: 'clubzone-1d568.firebasestorage.app',
    iosBundleId: 'com.example.ds2fcWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsnjzsO8cgcAbclG1y7vd5XvrXIQTyCCw',
    appId: '1:601121143669:web:40c16767489e181200713c',
    messagingSenderId: '601121143669',
    projectId: 'clubzone-1d568',
    authDomain: 'clubzone-1d568.firebaseapp.com',
    storageBucket: 'clubzone-1d568.firebasestorage.app',
    measurementId: 'G-521CGYEB1K',
  );
}
